AWSTemplateFormatVersion: '2010-09-09'
Description: Full VPC + ALB + ECS Fargate stack with environment prefix and execution role for ECR

Parameters:
  EnvName:
    Type: String
    Default: Dev
    Description: Environment name prefix

  VpcCidr:
    Type: String
    Default: 10.0.0.0/16

  PublicSubnet1Cidr:
    Type: String
    Default: 10.0.1.0/24

  PublicSubnet2Cidr:
    Type: String
    Default: 10.0.2.0/24

  PrivateSubnet1Cidr:
    Type: String
    Default: 10.0.101.0/24

  PrivateSubnet2Cidr:
    Type: String
    Default: 10.0.102.0/24

  AvailabilityZone1:
    Type: String
    Default: ap-southeast-2a

  AvailabilityZone2:
    Type: String
    Default: ap-southeast-2b

  ContainerImage:
    Type: String
    Default: "amazon/amazon-ecs-sample"
    Description: Docker image for the Fargate service

  InitialTaskCount:
    Type: Number
    Default: 2
    Description: The min/desired number of ECS tasks to run

  EcsClusterSuffix:
    Type: String
    Default: "EcsCluster"
    Description: Suffix for the ECS Cluster name

  EcsServiceSuffix:
    Type: String
    Default: "EcsService"
    Description: Suffix for the ECS Service name

  CloudfrontSecurityHeader:
    Type: String
    Default: "X-Origin-Verify"
    Description: Forces users to use Cloudfront instead of ALB. Forwarded from Cloudfront to the ALB and verified by the ALB.

  AlbAcmCertificateId:
    Type: String
    Default: c0c1681d-34f6-4691-ae71-fd08158d5466
    Description: ACM certificate ID for the ALB (must be in the same region as the stack)

  CloudFrontAcmCertificateId:
    Type: String
    Default: 627e39bb-164b-49ed-a211-6c190bbc413b
    Description: ACM certificate ID for CloudFront (must be in us-east-1)

  WebsiteDomain:
    Type: String
    Default: thefirecop.click
    Description: Alternate domain name (CNAME) for the CloudFront distribution

  Route53HostedZoneId:
    Type: String
    Default: Z10238621INYV4M8OF8YJ
    Description: Route53 hosted zone ID for the website domain

Resources:

  # #####################
  # # VPC, Subnets, IGW, NAT Gateway, Route Tables
  # #####################
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub "${EnvName}-MyVPC"

  MyIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${EnvName}-MyIGW"

  AttachIGW:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MyVPC
      InternetGatewayId: !Ref MyIGW

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: !Sub "${EnvName}-PublicRouteTable"

  PublicRouteInternet:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref MyIGW

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: !Ref PublicSubnet1Cidr
      AvailabilityZone: !Ref AvailabilityZone1
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${EnvName}-PublicSubnet1"

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: !Ref PublicSubnet2Cidr
      AvailabilityZone: !Ref AvailabilityZone2
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${EnvName}-PublicSubnet2"

  PublicSubnet1RTA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2RTA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  NatEIP:
    Type: AWS::EC2::EIP
    DependsOn: AttachIGW
    Properties:
      Domain: vpc

  MyNATGateway:
    Type: AWS::EC2::NatGateway
    DependsOn: AttachIGW
    Properties:
      AllocationId: !GetAtt NatEIP.AllocationId
      SubnetId: !Ref PublicSubnet1
      Tags:
        - Key: Name
          Value: !Sub "${EnvName}-MyNATGateway"

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: !Sub "${EnvName}-PrivateRouteTable"

  PrivateRouteNat:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref MyNATGateway

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: !Ref PrivateSubnet1Cidr
      AvailabilityZone: !Ref AvailabilityZone1
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub "${EnvName}-PrivateSubnet1"

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: !Ref PrivateSubnet2Cidr
      AvailabilityZone: !Ref AvailabilityZone2
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub "${EnvName}-PrivateSubnet2"

  PrivateSubnet1RTA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1
      RouteTableId: !Ref PrivateRouteTable

  PrivateSubnet2RTA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet2
      RouteTableId: !Ref PrivateRouteTable

  #####################
  # Security Groups
  #####################
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ALB SG
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub "${EnvName}-ALBSG"

  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ECS Tasks SG (only allow traffic from ALB)
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref ALBSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub "${EnvName}-ECSSG"

  #####################
  # ALB
  #####################
  MyALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "${EnvName}-ALB"
      Scheme: internet-facing
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      SecurityGroups:
        - !Ref ALBSecurityGroup
      Type: application

  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "${EnvName}-TargetGroup"
      VpcId: !Ref MyVPC
      Port: 80
      Protocol: HTTP
      TargetType: ip
      HealthCheckPath: /health

  #####################
  # ALB Listeners
  #####################
  ALBHttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref MyALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: "443"
            StatusCode: HTTP_301

  ALBHttpsListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref MyALB
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Sub arn:aws:acm:${AWS::Region}:${AWS::AccountId}:certificate/${AlbAcmCertificateId}
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            ContentType: text/plain
            MessageBody: Access is denied. You must use Cloudfront.
            StatusCode: "403"

  ALBHttpsListenerRuleWithHeader:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref ALBHttpsListener
      Priority: 1
      Conditions:
        - Field: http-header
          HttpHeaderConfig:
            HttpHeaderName: !Ref CloudfrontSecurityHeader
            Values:
              - '{{resolve:secretsmanager:XOriginVerifyHeaderValue}}'
      Actions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup

  #####################
  # ECS Cluster
  #####################
  MyECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${EnvName}-${EcsClusterSuffix}"

  #####################
  # ECS Task Execution Role
  #####################
  MyECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${EnvName}-ECSTaskExecutionRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Tags:
        - Key: Name
          Value: !Sub "${EnvName}-ECSTaskExecutionRole"

  #####################
  # ECS Task Definition
  #####################
  MyECSTaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${EnvName}-ECSTask"
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt MyECSTaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: app
          Image: !Ref ContainerImage
          PortMappings:
            - ContainerPort: 80
              Protocol: tcp

  #####################
  # ECS Service
  #####################
  MyECSService:
    Type: AWS::ECS::Service
    DependsOn: ALBHttpsListener
    Properties:
      ServiceName: !Sub "${EnvName}-${EcsServiceSuffix}"
      Cluster: !Ref MyECSCluster
      LaunchType: FARGATE
      TaskDefinition: !Ref MyECSTaskDef
      DesiredCount: !Ref InitialTaskCount
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref ECSSecurityGroup
          Subnets:
            - !Ref PrivateSubnet1
            - !Ref PrivateSubnet2
      LoadBalancers:
        - TargetGroupArn: !Ref ALBTargetGroup
          ContainerName: app
          ContainerPort: 80

  # #####################
  # # ECS Service Auto Scaling
  # #####################
  ECSServiceScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    DependsOn:
      - MyECSService
    Properties:
      MaxCapacity: 20
      MinCapacity: !Ref InitialTaskCount
      ResourceId: !Sub "service/${EnvName}-${EcsClusterSuffix}/${EnvName}-${EcsServiceSuffix}"
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  ECSServiceScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub "${EnvName}-ECSServiceScalingPolicy"
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref ECSServiceScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 2.0
        PredefinedMetricSpecification:
          PredefinedMetricType: ALBRequestCountPerTarget
          ResourceLabel: !Sub "${MyALB.LoadBalancerFullName}/${ALBTargetGroup.TargetGroupFullName}"
        ScaleInCooldown: 10
        ScaleOutCooldown: 10
  
  #####################
  # CloudFront
  #####################
  MyCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DeletionPolicy: Retain
    Properties:
      DistributionConfig:
        Enabled: true
        HttpVersion: http2
        Comment: !Sub "${EnvName}"
        Aliases:
        - !Ref WebsiteDomain
        ViewerCertificate:
          AcmCertificateArn: !Sub arn:aws:acm:us-east-1:${AWS::AccountId}:certificate/${CloudFrontAcmCertificateId}
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Origins:
          - Id: ALBOrigin
            DomainName: !GetAtt MyALB.DNSName
            CustomOriginConfig:
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
            OriginCustomHeaders:
              - HeaderName: !Ref CloudfrontSecurityHeader
                HeaderValue: '{{resolve:secretsmanager:XOriginVerifyHeaderValue}}'
        DefaultCacheBehavior:
          TargetOriginId: ALBOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD]
          CachedMethods: [GET, HEAD]
          Compress: true
          # UseOriginCacheControlHeaders-QueryStrings Policy ID
          CachePolicyId: 4cc15a8a-d715-48a4-82b8-cc0b614638fe

  #####################
  # Route53 Records
  #####################
  WebsiteAliasARecord:
    Type: AWS::Route53::RecordSet
    DependsOn: MyCloudFrontDistribution
    Properties:
      HostedZoneId: !Ref Route53HostedZoneId
      Name: !Ref WebsiteDomain
      Type: A
      AliasTarget:
        DNSName: !GetAtt MyCloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
        EvaluateTargetHealth: false

  WebsiteAliasAAAARecord:
    Type: AWS::Route53::RecordSet
    DependsOn: MyCloudFrontDistribution
    Properties:
      HostedZoneId: !Ref Route53HostedZoneId
      Name: !Ref WebsiteDomain
      Type: AAAA
      AliasTarget:
        DNSName: !GetAtt MyCloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
        EvaluateTargetHealth: false
